#Migration resume state
#Tue Mar 24 16:21:23 ICT 2026
EMPLOYEES.offset=0
EMPLOYEE_AUDIT.done=true
DEPARTMENT.offset=0
DEPARTMENTS.offset=0
EMPLOYEE.done=true
EMPLOYEES.done=true
EMPLOYEE_AUDIT.offset=0
DEPARTMENTS.done=true
DEPARTMENT.done=true
EMPLOYEE.offset=0
