-- Demo metadata objects for PostgreSQL schema (public)

DROP TABLE IF EXISTS employee_audit CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS departments CASCADE;

CREATE TABLE departments (
    department_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    department_code VARCHAR(20) NOT NULL,
    department_name VARCHAR(120) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_departments PRIMARY KEY (department_id),
    CONSTRAINT uq_departments_code UNIQUE (department_code)
);

CREATE TABLE employees (
    employee_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    department_id INTEGER NOT NULL,
    employee_code VARCHAR(30) NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    salary NUMERIC(12, 2),
    hired_at DATE NOT NULL DEFAULT CURRENT_DATE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_employees PRIMARY KEY (employee_id),
    CONSTRAINT uq_employees_code UNIQUE (employee_code),
    CONSTRAINT fk_employees_departments FOREIGN KEY (department_id)
        REFERENCES departments (department_id)
);

CREATE TABLE employee_audit (
    audit_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    employee_id INTEGER NOT NULL,
    action_type VARCHAR(20) NOT NULL,
    action_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_employee_audit PRIMARY KEY (audit_id),
    CONSTRAINT fk_employee_audit_employees FOREIGN KEY (employee_id)
        REFERENCES employees (employee_id)
);

CREATE INDEX idx_employees_department_id ON employees (department_id);
CREATE INDEX idx_employee_audit_employee_id ON employee_audit (employee_id);

INSERT INTO departments (department_code, department_name)
VALUES ('ENG', 'Engineering'), ('OPS', 'Operations');

INSERT INTO employees (department_id, employee_code, full_name, salary, is_active)
VALUES
    (1, 'EMP001', 'Alice Nguyen', 1800.50, TRUE),
    (2, 'EMP002', 'Bob Tran', 1600.00, TRUE);

INSERT INTO employee_audit (employee_id, action_type)
VALUES (1, 'CREATED'), (2, 'CREATED');
